run:
	mix run -e "ElixirDay01.main()"
big:
	mix run -e "ElixirDay01.Big.main()"
big_naive:
	mix run -e "ElixirDay01.BigNaive.main()"
big_flow:
	mix run -e "ElixirDay01.BigFlow.main()"
.PHONY: test
test:
	mix test
repl:
	iex
format:
	mix format
