# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rspec", "~> 3.9"
gem "prettier", "~> 0.16.0"

gem "require_all", "~> 3.0"
